'''
Run this script, to remove dark images from the image folder generated by 01_TestGammaCorrection
Dark images are moved to a folder "dark", where they can be inspected.
After this process, run "CleanLogs.py" or further filter scripts
'''


import cv2 as cv
import numpy as np
import os

#
# prepare
path = "G:/LOGDATA_CPS/11_24/test/img"
pathTarget = "G:/LOGDATA_CPS/11_24/test/dark"
os.mkdir(pathTarget)
#
# collect
print("Collecting files from ", path)
imgFiles = [f for f in os.listdir(path) if os.path.isfile(os.path.join(path, f))]
print("Total number: ", len(imgFiles))
#
# analyze and move
cnt = 0
for imName in imgFiles:
    img = cv.imread(os.path.join(path, imName))
    hist = np.histogram(img, bins=256, range = (0, 256))
    bins = hist[1][0:-1]
    sumHist = np.sum(hist[0])
    meanHist = np.sum(bins * hist[0]) / sumHist
    binsN = bins - meanHist
    std = np.sum(binsN *binsN * hist[0]) / sumHist

    print(cnt, meanHist, std)
    if meanHist < 40:
        if std < 250:
            cv.imwrite(os.path.join(pathTarget, imName), img)
            os.remove(os.path.join(path, imName))
            print("^^^^^^^^^^^")
    
    cnt += 1
    if cnt > 10000:
        break
