'''
Run this script, to remove images containing a QR code from the image folder generated by 01_TestGammaCorrection
Dark images are moved to a folder "QR", where they can be inspected.
After this process, run "04_CleanLogs.py"
'''


import cv2 as cv
import numpy as np
import os

#
# prepare
path = "G:/LOGDATA_CPS/11_24/test/img"
pathTarget = "G:/LOGDATA_CPS/11_24/test/QR"
os.mkdir(pathTarget)
#
# collect
print("Collecting files from ", path)
imgFiles = [f for f in os.listdir(path) if os.path.isfile(os.path.join(path, f))]
print("Total number: ", len(imgFiles))
#
# analyze and move
cnt = 0
qrCodeDetector = cv.QRCodeDetector()
for imName in imgFiles:
    img = cv.imread(os.path.join(path, imName))
    text, points, _ = qrCodeDetector.detectAndDecode(img)
    print(cnt, text)
    if not points is None:
        cv.imwrite(os.path.join(pathTarget, imName), img)
        os.remove(os.path.join(path, imName))
        print("^^^^^^^^^^^")
    cnt += 1
    if cnt > 10000:
        break
